# Generated by Django 3.1.4 on 2020-12-28 21:57

from django.db import migrations, models
import django.db.models.deletion
import hookah.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Hookah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Price')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Is Premium?')),
                ('color', models.PositiveSmallIntegerField(choices=[(1, 'yellow'), (2, 'black'), (3, 'white')], default=2, verbose_name='Color')),
                ('image', models.ImageField(blank=True, null=True, upload_to=hookah.utils.image_upload_location, verbose_name='image')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hookah', to='hookah.company')),
            ],
            options={
                'verbose_name': 'Hookah',
                'verbose_name_plural': 'Hookahs',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('hookah', models.ManyToManyField(blank=True, related_name='Country', to='hookah.Hookah')),
            ],
        ),
    ]
