# Generated by Django 3.1.4 on 2020-12-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hookah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(default=9, unique=True, verbose_name='Tax number'),
            preserve_default=False,
        ),
    ]
