# Generated by Django 3.1.4 on 2020-12-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hookah', '0002_company_tax_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-name'], 'verbose_name': 'company', 'verbose_name_plural': 'Companys'},
        ),
    ]
