# Generated by Django 3.1.4 on 2020-12-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hookah', '0003_auto_20201229_0052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countrys'},
        ),
    ]
